-- WorkPulse schema — PostgreSQL edition (Neon, Supabase, any Postgres).
-- Applied automatically on first boot when DATABASE_URL starts with postgres://.
-- Safe to re-run: everything is IF NOT EXISTS. Mirrors schema.sql (MySQL) exactly.

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(30) NULL UNIQUE,
  email VARCHAR(190) NULL UNIQUE,
  role VARCHAR(10) NOT NULL DEFAULT 'doer' CHECK (role IN ('owner','manager','doer')),
  password_hash VARCHAR(100) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- One-off assigned tasks (the old "Delegation" sheet).
CREATE TABLE IF NOT EXISTS delegations (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_task_id VARCHAR(30) NULL UNIQUE,
  doer_id INTEGER NOT NULL REFERENCES users(id),
  description VARCHAR(500) NOT NULL,
  first_date DATE NOT NULL,
  due_date DATE NOT NULL,
  revision_1_date DATE NULL,
  revision_2_date DATE NULL,
  latest_revision_date DATE NULL,
  total_revisions INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(15) NOT NULL DEFAULT 'assigned' CHECK (status IN ('assigned','completed','week_shifted')),
  completed_at DATE NULL,
  created_by INTEGER NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_delegations_doer ON delegations (doer_id);
CREATE INDEX IF NOT EXISTS idx_delegations_due ON delegations (due_date);
CREATE INDEX IF NOT EXISTS idx_delegations_status ON delegations (status);

-- Standing responsibilities: FMS (follow-ups) and Checklist share one shape.
CREATE TABLE IF NOT EXISTS recurring_items (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  type VARCHAR(10) NOT NULL CHECK (type IN ('fms','checklist')),
  name VARCHAR(200) NOT NULL,
  doer_id INTEGER NOT NULL REFERENCES users(id),
  method VARCHAR(500) NULL,
  frequency VARCHAR(10) NOT NULL DEFAULT 'weekly' CHECK (frequency IN ('daily','weekly','monthly')),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_recurring_items_doer ON recurring_items (doer_id);
CREATE INDEX IF NOT EXISTS idx_recurring_items_type ON recurring_items (type);

-- One row per review cycle per recurring item (generated by the daily job).
CREATE TABLE IF NOT EXISTS recurring_entries (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  recurring_item_id INTEGER NOT NULL REFERENCES recurring_items(id) ON DELETE CASCADE,
  cycle_label VARCHAR(20) NOT NULL,
  planned_date DATE NOT NULL,
  actual_date DATE NULL,
  status VARCHAR(10) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','done','missed')),
  delay_days INTEGER NULL,
  UNIQUE (recurring_item_id, cycle_label)
);
CREATE INDEX IF NOT EXISTS idx_entries_planned ON recurring_entries (planned_date);

-- Precomputed weekly scores (Sunday-to-Saturday weeks).
CREATE TABLE IF NOT EXISTS weekly_scores (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  doer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  week_number INTEGER NOT NULL,
  week_start DATE NOT NULL,
  week_end DATE NOT NULL,
  planned_count INTEGER NOT NULL DEFAULT 0,
  actual_count INTEGER NOT NULL DEFAULT 0,
  score NUMERIC(6,2) NOT NULL DEFAULT 0,
  rating VARCHAR(10) NOT NULL CHECK (rating IN ('red','yellow','green')),
  computed_at TIMESTAMP NOT NULL,
  UNIQUE (doer_id, week_start)
);
CREATE INDEX IF NOT EXISTS idx_scores_week ON weekly_scores (week_start);

-- Configurable rating bands: a score >= min_score earns that rating.
CREATE TABLE IF NOT EXISTS score_thresholds (
  rating VARCHAR(10) PRIMARY KEY CHECK (rating IN ('red','yellow','green')),
  min_score NUMERIC(6,2) NOT NULL
);

-- Audit trail: who did what, when.
CREATE TABLE IF NOT EXISTS activity_log (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id INTEGER NULL,
  action VARCHAR(40) NOT NULL,
  detail VARCHAR(300) NULL,
  subject_user_id INTEGER NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_activity_created ON activity_log (created_at);
CREATE INDEX IF NOT EXISTS idx_activity_subject ON activity_log (subject_user_id);
