-- WorkPulse schema
-- Runs automatically on first boot (server.js -> ensureSchema). Safe to re-run: everything is IF NOT EXISTS.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(30) NULL,
  email VARCHAR(190) NULL,
  role ENUM('owner','manager','doer') NOT NULL DEFAULT 'doer',
  password_hash VARCHAR(100) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email),
  UNIQUE KEY uq_users_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- One-off assigned tasks (the old "Delegation" sheet).
-- first_date = original committed deadline, due_date = current effective deadline.
-- Revisions preserved so "how many times did the deadline slip" stays visible.
CREATE TABLE IF NOT EXISTS delegations (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_task_id VARCHAR(30) NULL,
  doer_id INT UNSIGNED NOT NULL,
  description VARCHAR(500) NOT NULL,
  first_date DATE NOT NULL,
  due_date DATE NOT NULL,
  revision_1_date DATE NULL,
  revision_2_date DATE NULL,
  latest_revision_date DATE NULL,
  total_revisions INT NOT NULL DEFAULT 0,
  status ENUM('assigned','completed','week_shifted') NOT NULL DEFAULT 'assigned',
  completed_at DATE NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_delegations_task (public_task_id),
  KEY idx_delegations_doer (doer_id),
  KEY idx_delegations_due (due_date),
  KEY idx_delegations_status (status),
  CONSTRAINT fk_delegations_doer FOREIGN KEY (doer_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Standing responsibilities: FMS (follow-ups) and Checklist share one shape.
CREATE TABLE IF NOT EXISTS recurring_items (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  type ENUM('fms','checklist') NOT NULL,
  name VARCHAR(200) NOT NULL,
  doer_id INT UNSIGNED NOT NULL,
  method VARCHAR(500) NULL,
  frequency ENUM('daily','weekly','monthly') NOT NULL DEFAULT 'weekly',
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_recurring_items_doer (doer_id),
  KEY idx_recurring_items_type (type),
  CONSTRAINT fk_recurring_items_doer FOREIGN KEY (doer_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- One row per review cycle per recurring item (generated by the daily job).
CREATE TABLE IF NOT EXISTS recurring_entries (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  recurring_item_id INT UNSIGNED NOT NULL,
  cycle_label VARCHAR(20) NOT NULL,
  planned_date DATE NOT NULL,
  actual_date DATE NULL,
  status ENUM('pending','done','missed') NOT NULL DEFAULT 'pending',
  delay_days INT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_entries_cycle (recurring_item_id, cycle_label),
  KEY idx_entries_planned (planned_date),
  CONSTRAINT fk_entries_item FOREIGN KEY (recurring_item_id) REFERENCES recurring_items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Precomputed weekly scores (Sunday-to-Saturday weeks).
-- score = min(0, max(-100, (actual/planned - 1) * 100))
CREATE TABLE IF NOT EXISTS weekly_scores (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  doer_id INT UNSIGNED NOT NULL,
  week_number INT NOT NULL,
  week_start DATE NOT NULL,
  week_end DATE NOT NULL,
  planned_count INT NOT NULL DEFAULT 0,
  actual_count INT NOT NULL DEFAULT 0,
  score DECIMAL(6,2) NOT NULL DEFAULT 0,
  rating ENUM('red','yellow','green') NOT NULL,
  computed_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_scores_doer_week (doer_id, week_start),
  KEY idx_scores_week (week_start),
  CONSTRAINT fk_scores_doer FOREIGN KEY (doer_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Configurable rating bands: a score >= min_score earns that rating
-- (evaluated best rating first). Seeded on first boot: green -10, yellow -30, red -100.
CREATE TABLE IF NOT EXISTS score_thresholds (
  rating ENUM('red','yellow','green') NOT NULL,
  min_score DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (rating)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Audit trail: who did what, when. Written by the app on every meaningful action.
CREATE TABLE IF NOT EXISTS activity_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NULL,
  action VARCHAR(40) NOT NULL,
  detail VARCHAR(300) NULL,
  subject_user_id INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_activity_created (created_at),
  KEY idx_activity_subject (subject_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
